github: [jasonfb]
custom: ["https://heliosdev.shop/p/universal-track-manager/?utm_source=github.com&utm_campaign=github_universal_track_manager_repo_funding_link",
         "https://shop.heliosdev.shop/?utm_source=github.com&utm_campaign=github_universal_track_manager_repo_funding_link"]

