language: ruby

before_install:
  - gem update --system

install:
  - "bin/setup"

branches:
  only:
    - master

gemfile:
  - gemfiles/rails_6_0.gemfile

script: "bundle exec rake spec"

rvm:
  - 2.6
