source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gemspec

gem 'minitest'
gem 'minitest-rg'
gem 'mocha'
gem 'simplecov'

# gem 'rspec-rails'
# gem 'sqlite3'

# require 'minitest/unit'
# require 'mocha/minitest'

gem 'byebug', group: [:development, :test]


