# begin
#   require 'bundler/setup'
# rescue LoadError
#   puts 'You must `gem install bundler` and `bundle install` to run rake tasks'
# end

require 'rdoc/task'

RDoc::Task.new(:rdoc) do |rdoc|
  rdoc.rdoc_dir = 'rdoc'
  rdoc.title    = 'UniversalTrackManager'
  rdoc.options << '--line-numbers'
  rdoc.rdoc_files.include('README.md')
  rdoc.rdoc_files.include('lib/**/*.rb')
end

require 'bundler/gem_tasks'

require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.libs << 'test'
  t.libs << 'lib'
  t.libs << 'lib/generators'
  t.libs << 'lib/tasks'
  t.libs << 'lib/universal_track_manager'

  t.pattern = 'test/**/*_test.rb'
  t.verbose = false
end

task default: :test



# desc "Run tests"
task :default => :test

task :console do
  require 'irb'
  require 'irb/completion'
  require 'universal_track_manager'
  ARGV.clear
  IRB.start
end


