require "rubygems"
# require "bundler/setup"
require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << 'test'
  t.libs << 'lib'
  t.libs << 'lib/generators'
  t.libs << 'lib/tasks'
  t.libs << 'lib/universal_track_manager'
  t.pattern = 'test/**/*_test.rb'
end

desc "Run tests"
task :default => :test

task :console do
  require 'irb'
  require 'irb/completion'
  require 'universal_track_manager'
  ARGV.clear
  IRB.start
end


